import Feed from "@/components/Feed";
import Header from "@/components/Header";
import Modal from "@/components/Modal";
import Head from "next/head";

export default function Home() {
  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">
      <Head>
        <title>InstaGram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Header */}
        <Header />
        {/* Feed */}
        <Feed />
        {/* Modal */}
        <Modal />
      </main>
    </div>
  );
}
